name: szm_reader
publish_to: 'none'
description: A cross-platform text reader supporting Android and HarmonyOS.
version: 0.1.0+1
environment:
  sdk: '>=2.17.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.1.2
  intl: ^0.19.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
